/**
 * Push notification API
 * ### API per invio di notifiche push personalizzate agli utenti dell'applicazione RCA SUPPORT  Il servizio di assistenza dell'azienda RCA SRL prevede l'utilizzo di un'applicazione  multipiattaforma (Android, iOS, Web App) chiamata RCA SUPPORT, lo scopo principale di queste api  è l'invio di notifiche push personalizzate agli utenti dell'applicazione  #### Push notification token Ad ogni dispositivo client dell'applicazione viene automaticamente associato un token,  necessario per inviare una notifica push diretta al dispositivo. Tutti i token vengono salvati in un database SQL dove sono presenti i dati sui clienti dell'azienda, ad ogni token viene associato un cliente ed un locale.  #### Firebase Admin SDK e Firebase cloud Messaging (FCM) Il servizio utilizzato per l'invio delle notifiche push è FCM, ed è strutturato in questo modo:  - *Generatore di messaggi e target:*      si occupa della creazione dei messaggi creando delle triplette titolo, descrizione, token che vengono inviate al backend FCM tramite Firebase Admin SDK  - *FCM backend:* legge i dati inviati dal generatore, genera i metadati del messaggio e li invia agli instradatori  - *Instradatori di messaggi specifici della piattaforma:*     - **Android Trasport Layer** per dispositivi Android     - **iOS / APNs** per dispositivi iOS     - **Web Push** per app web  - *SDK sul dispositivo:* viene visualizzata la notifica o il messaggio viene gestito in base allo stato in primo piano / in background dell'app e a qualsiasi logica dell'applicazione pertinente.  #### Analisi dei requisiti  Lo scopo di questa API è quello di **Generatore di messaggi e target**, in particolare si occupa di:  1. Interazione con database SQL dove sono salvati i dati 2. Utilizzo del servizio FCM (Firebase Cloud Messaging) per l'invio delle notifiche push  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserinfoHttpspushapiusauth0comuserMetadata from './UserinfoHttpspushapiusauth0comuserMetadata';

/**
* The Userinfo model module.
* @module model/Userinfo
* @version 1.0.0
*/
export default class Userinfo {
    /**
    * Constructs a new <code>Userinfo</code>.
    * @alias module:model/Userinfo
    * @class
    * @param sub {String} auth0 user id
    * @param nickname {String} auth0 user nickname
    * @param name {String} auth0 user name
    * @param picture {String} auth0 user picture
    * @param updatedAt {String} auth0 user last update
    * @param email {String} auth0 user email
    * @param emailVerified {Boolean} auth0 user email verified
    * @param httpspushApiusauth0comuserMetadata {module:model/UserinfoHttpspushapiusauth0comuserMetadata} 
    */

    constructor(sub, nickname, name, picture, updatedAt, email, emailVerified, httpspushApiusauth0comuserMetadata) {
        
        
        this['sub'] = sub;
        this['nickname'] = nickname;
        this['name'] = name;
        this['picture'] = picture;
        this['updated_at'] = updatedAt;
        this['email'] = email;
        this['email_verified'] = emailVerified;
        this['https://push-api:us:auth0:com/user_metadata'] = httpspushApiusauth0comuserMetadata;
        
    }

    /**
    * Constructs a <code>Userinfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Userinfo} obj Optional instance to populate.
    * @return {module:model/Userinfo} The populated <code>Userinfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Userinfo();
                        
            
            if (data.hasOwnProperty('sub')) {
                obj['sub'] = ApiClient.convertToType(data['sub'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('email_verified')) {
                obj['email_verified'] = ApiClient.convertToType(data['email_verified'], 'Boolean');
            }
            if (data.hasOwnProperty('https://push-api:us:auth0:com/user_metadata')) {
                obj['https://push-api:us:auth0:com/user_metadata'] = UserinfoHttpspushapiusauth0comuserMetadata.constructFromObject(data['https://push-api:us:auth0:com/user_metadata']);
            }
        }
        return obj;
    }

    /**
    * auth0 user id
    * @member {String} sub
    */
    'sub' = undefined;
    /**
    * auth0 user nickname
    * @member {String} nickname
    */
    'nickname' = undefined;
    /**
    * auth0 user name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * auth0 user picture
    * @member {String} picture
    */
    'picture' = undefined;
    /**
    * auth0 user last update
    * @member {String} updated_at
    */
    'updated_at' = undefined;
    /**
    * auth0 user email
    * @member {String} email
    */
    'email' = undefined;
    /**
    * auth0 user email verified
    * @member {Boolean} email_verified
    */
    'email_verified' = undefined;
    /**
    * @member {module:model/UserinfoHttpspushapiusauth0comuserMetadata} https://push-api:us:auth0:com/user_metadata
    */
    'https://push-api:us:auth0:com/user_metadata' = undefined;




}
